Repository wecode-bootcamp-korea/16-2nd-bearbnb-frontend, pull requests merged in 2021-02, with the labels that each got.

#1 [16기 태성현] Feature/list 작업중
  .gitignore
  package-lock.json
  package.json
  public/images/chat.png
  public/images/chat.svg
  public/images/chat2.png
  public/images/label copy.png
  public/images/label.png
  public/images/paw.png
  public/images/star.png
  src/Components/ImgSlider/ImgSlider.js
  src/Components/ImgSlider/ImgSlider.scss
  src/Components/Nav/Nav.scss
  src/Map.js
  src/Pages/List/Availables/Availables.js
  src/Pages/List/Availables/Availables.scss
  src/Pages/List/Availables/PaginationBtns/PaginationBtns.js
  src/Pages/List/Availables/PaginationBtns/PaginationBtns.scss
  src/Pages/List/Data.js
  src/Pages/List/Filters/FilterModals/AddFilter.js
  src/Pages/List/Filters/FilterModals/Price.js
  src/Pages/List/Filters/FilterModals/RefundPolicy.js
  src/Pages/List/Filters/FilterModals/Type.js
  src/Pages/List/Filters/Filters.js
  src/Pages/List/Filters/Filters.scss
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/Pages/List/MapContainer/Components/Detail.js
  src/Pages/List/MapContainer/Components/Detail.scss
  src/Pages/List/MapContainer/GoogleMap.js
  src/Pages/List/MapContainer/GoogleMap.scss
  src/Pages/List/MapContainer/Marker.js
  src/Pages/List/MapContainer/Marker.scss
  src/Styles/Common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#7 [16기 정민선] 네브 수정사항 반영
  src/Components/Nav/Components/Logo/Logo.js
  src/Components/Nav/Components/Logo/Logo.scss
  src/Components/Nav/Components/Profile/Profile.scss
  src/Components/Nav/Components/SearchContainer/Components/CheckInOutDate/CheckInOutDate.js
  src/Components/Nav/Components/SearchContainer/Components/CheckInOutDate/CheckInOutDate.scss
  src/Components/Nav/Components/SearchContainer/Components/Guests/Guests.scss
  src/Components/Nav/Components/SearchContainer/Components/Location/Location.scss
  src/Components/Nav/Components/SearchContainer/Components/SearchBar/CalendarCustom.scss
  src/Components/Nav/Components/SearchContainer/Components/SearchBar/SearchBar.js
  src/Components/Nav/Components/SearchContainer/Components/SearchBar/SearchBar.scss
  src/Components/Nav/Components/SearchContainer/SearchContainer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/Navbar.js
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: Accepted

#9 [16기 정민선] 푸터 레이아웃 작업 완료
  public/data/Footer.json
  public/images/Footer/facebook.png
  public/images/Footer/instagram.png
  public/images/Footer/twitter.png
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#8 [16기 정민선] 검색기능 구현 완료
  public/data/search.json
  src/Components/Nav/Components/SearchContainer/Components/Location/Location.js
  src/Components/Nav/Components/SearchContainer/Components/Location/Location.scss
  src/Components/Nav/Components/SearchContainer/Components/SearchBar/SearchBar.js
  src/Components/Nav/Components/SearchContainer/Components/SearchBar/SearchBar.scss
  src/Components/Nav/Components/SearchContainer/SearchContainer.js
  src/Components/Nav/Nav.scss
Labels: Status: 수정 요청

#5 [16기 정민선] 소셜 로그인 구현 완료
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/Pages/SocialLogin/SocialLogin.js
  src/config.js
Labels: Status: 리뷰 요청

#3 [16기 김승완] 로그인,회원가입 리팩토링 작업시작
  package-lock.json
  package.json
  public/images/close.svg
  public/images/emailBlack.svg
  public/images/emailWhite.svg
  public/images/signLock.svg
  public/images/signUpEye.svg
  public/images/signUpEye2.svg
  public/images/signUpUser.svg
  src/Components/Nav/Components/Profile/Components/ProfileBox.js
  src/Components/Nav/Components/Profile/Profile.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/List/List.js
  src/Pages/Login/Login.scss
  src/Pages/Modal/Components/Button.js
  src/Pages/Modal/Components/Form.js
  src/Pages/Modal/Components/Input.js
  src/Pages/Modal/Components/Line.js
  src/Pages/Modal/Components/SignIn.js
  src/Pages/Modal/Components/SignPage.js
  src/Pages/Modal/Components/SignUp.js
  src/Pages/Modal/Components/UploadImg.js
  src/Pages/Modal/Data/ModalData.js
  src/Pages/Modal/Modal.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/config.js
Labels: Status: 컨플릭트 해결 요청

#6 [16기 정민선] 상세 페이지 기능 구현 중
  .gitignore
  public/data/Review.json
  public/data/SpaceDetail.json
  public/data/detailData.json
  public/data/search.json
  public/images/Detail/bed.png
  public/images/Detail/down-arrow.png
  public/images/Detail/heart.png
  public/images/Detail/home.png
  public/images/Detail/marker.png
  public/images/Detail/medal.png
  public/images/Detail/shield.png
  public/images/Detail/sofa.png
  public/images/Detail/star.png
  public/images/Detail/up-arrow.png
  public/images/Detail/upload.png
  public/index.html
  src/Components/Footer/Footer.scss
  src/Components/Nav/Components/SearchContainer/SearchContainer.js
  src/Pages/DetailPage/Components/BedType.js
  src/Pages/DetailPage/Components/Facility.js
  src/Pages/DetailPage/Components/Header.js
  src/Pages/DetailPage/Components/HostInfo.js
  src/Pages/DetailPage/Components/HostInfoDetail.js
  src/Pages/DetailPage/Components/Location.js
  src/Pages/DetailPage/Components/MenuTab/MenuTab.js
  src/Pages/DetailPage/Components/PhotoContainer.js
  src/Pages/DetailPage/Components/ReservationBox/Components/ButtonBox.js
  src/Pages/DetailPage/Components/ReservationBox/Components/Calendar.js
  src/Pages/DetailPage/Components/ReservationBox/Components/Calendar.scss
  src/Pages/DetailPage/Components/ReservationBox/Components/GuestBoxList.js
  src/Pages/DetailPage/Components/ReservationBox/Components/PriceDetail.js
  src/Pages/DetailPage/Components/ReservationBox/Components/ReservationButton.js
  src/Pages/DetailPage/Components/ReservationBox/ReservationBox.js
  src/Pages/DetailPage/Components/ReviewList.js
  src/Pages/DetailPage/DetailPage.js
  src/Routes.js
Labels: Status: 리뷰 요청

#10 [16기 태성현] Feature/map 리스트페이지 맵 및 리스트 필터
  src/Components/ImgSlider/ImgSlider.js
  src/Components/ImgSlider/ImgSlider.scss
  src/Pages/List/Availables/Availables.js
  src/Pages/List/Availables/Availables.scss
  src/Pages/List/Availables/PaginationBtns/PaginationBtns.js
  src/Pages/List/Data.js
  src/Pages/List/Filters/FilterModals/AddFilter.js
  src/Pages/List/Filters/FilterModals/BottomButtons.js
  src/Pages/List/Filters/FilterModals/Price.js
  src/Pages/List/Filters/FilterModals/RefundPolicy.js
  src/Pages/List/Filters/FilterModals/Type.js
  src/Pages/List/Filters/Filters.js
  src/Pages/List/Filters/Filters.scss
  src/Pages/List/GoogleMap/Components/Detail.js
  src/Pages/List/GoogleMap/Components/Detail.scss
  src/Pages/List/GoogleMap/GoogleMap.js
  src/Pages/List/GoogleMap/GoogleMap.scss
  src/Pages/List/GoogleMap/Marker.js
  src/Pages/List/GoogleMap/Marker.scss
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/config.js
Labels: Status: 리뷰 요청

#11 [16기 김승완] 소셜로그인 및 네브바와 합치는 작업
  public/index.html
  src/Pages/Modal/Components/Button.js
  src/Pages/Modal/Components/SignIn.js
Labels: Status: Accepted

#12 [16기 정민선]로딩 화면 추가
  src/Pages/DetailPage/DetailPage.js
  src/Pages/List/List.js
  src/Pages/List/List.scss
  src/config.js
Labels: Status: 리뷰 요청
